// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-vkwYxy9oPHpqBShkhfJSA3s2DpKNHy8',
    appId: '1:82187038962:web:089834ed18203c1f39e06b',
    messagingSenderId: '82187038962',
    projectId: 'belajar-flutter-bd6b5',
    authDomain: 'belajar-flutter-bd6b5.firebaseapp.com',
    databaseURL: 'https://belajar-flutter-bd6b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-flutter-bd6b5.firebasestorage.app',
    measurementId: 'G-F6JE4VG4EQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsPXKWFaAKdNcmtF9OTCTQ9QPQksv8ZQs',
    appId: '1:82187038962:android:f55e15313938141b39e06b',
    messagingSenderId: '82187038962',
    projectId: 'belajar-flutter-bd6b5',
    databaseURL: 'https://belajar-flutter-bd6b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-flutter-bd6b5.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDdggcgF8S_LTmfrJoKdkaMBjmp-OEUbM',
    appId: '1:82187038962:ios:7c887bb83c6a172f39e06b',
    messagingSenderId: '82187038962',
    projectId: 'belajar-flutter-bd6b5',
    databaseURL: 'https://belajar-flutter-bd6b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-flutter-bd6b5.firebasestorage.app',
    iosBundleId: 'com.example.gamesParentingControl',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDdggcgF8S_LTmfrJoKdkaMBjmp-OEUbM',
    appId: '1:82187038962:ios:7c887bb83c6a172f39e06b',
    messagingSenderId: '82187038962',
    projectId: 'belajar-flutter-bd6b5',
    databaseURL: 'https://belajar-flutter-bd6b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-flutter-bd6b5.firebasestorage.app',
    iosBundleId: 'com.example.gamesParentingControl',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-vkwYxy9oPHpqBShkhfJSA3s2DpKNHy8',
    appId: '1:82187038962:web:69b7b8c8e47ae9ec39e06b',
    messagingSenderId: '82187038962',
    projectId: 'belajar-flutter-bd6b5',
    authDomain: 'belajar-flutter-bd6b5.firebaseapp.com',
    databaseURL: 'https://belajar-flutter-bd6b5-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'belajar-flutter-bd6b5.firebasestorage.app',
    measurementId: 'G-YK47GE32S3',
  );
}
