org.gradle.jvmargs=-Xmx8G -XX:MaxMetaspaceSize=4G -XX:ReservedCodeCacheSize=512m -XX:+HeapDumpOnOutOfMemoryError
android.useAndroidX=true
android.aapt2FromMavenOverride=/nix/store/d0a2jn5xrp9mplyrr6fabzl43620i144-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/d0a2jn5xrp9mplyrr6fabzl43620i144-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/d0a2jn5xrp9mplyrr6fabzl43620i144-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/d0a2jn5xrp9mplyrr6fabzl43620i144-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/d0a2jn5xrp9mplyrr6fabzl43620i144-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/d0a2jn5xrp9mplyrr6fabzl43620i144-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/d0a2jn5xrp9mplyrr6fabzl43620i144-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/d0a2jn5xrp9mplyrr6fabzl43620i144-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/la40ndna0blcpbhfvc95zid0fmvnxxp0-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
android.aapt2FromMavenOverride=/nix/store/29hwgyycy2477znfzakqpmdlws2hh8ic-androidsdk/libexec/android-sdk/build-tools/35.0.0/aapt2
