import 'dart:convert';
import 'package:crypto/crypto.dart';

/// Payload carried inside an unlock QR code generated by the parent app.
class QrUnlockPayload {
  final String kidId;
  final int extraMinutes;
  final int expiresAt; // Unix ms
  final String hmac;

  const QrUnlockPayload({
    required this.kidId,
    required this.extraMinutes,
    required this.expiresAt,
    required this.hmac,
  });

  Map<String, dynamic> toMap() => {
        'type': 'unlock',
        'kidId': kidId,
        'extraMinutes': extraMinutes,
        'expiresAt': expiresAt,
        'hmac': hmac,
      };

  factory QrUnlockPayload.fromMap(Map<String, dynamic> map) => QrUnlockPayload(
        kidId: map['kidId'] as String,
        extraMinutes: map['extraMinutes'] as int,
        expiresAt: map['expiresAt'] as int,
        hmac: map['hmac'] as String,
      );
}

/// Payload carried inside a pairing QR code generated by the parent app.
class QrPairingPayload {
  final String familyId;
  final String appVersion;

  const QrPairingPayload({
    required this.familyId,
    this.appVersion = '1',
  });

  Map<String, dynamic> toMap() => {
        'type': 'pair',
        'familyId': familyId,
        'appVersion': appVersion,
      };

  factory QrPairingPayload.fromMap(Map<String, dynamic> map) =>
      QrPairingPayload(
        familyId: map['familyId'] as String,
        appVersion: (map['appVersion'] as String?) ?? '1',
      );
}

/// Handles generation and verification of QR codes for:
///  - Unlock (extra play time granted by parent)
///  - Pairing (linking kids device to parent family)
///
/// Uses HMAC-SHA256 for signing unlock QRs to prevent forgery (SEC-05).
class QrUnlockService {
  static const int _expiryWindowMs = 5 * 60 * 1000; // 5 minutes

  // ─── UNLOCK QR ────────────────────────────────────────────────────────────

  /// Generate a signed unlock QR payload string.
  /// Called from the **parent** app when "Give extra time" is tapped.
  ///
  /// [otpSecret] is the family's OTP secret stored in secure storage.
  static String generateUnlockQr({
    required String kidId,
    required int extraMinutes,
    required String otpSecret,
  }) {
    final expiresAt =
        DateTime.now().millisecondsSinceEpoch + _expiryWindowMs;
    final message = '$kidId:$extraMinutes:$expiresAt';
    final hmac = _computeHmac(message, otpSecret);

    final payload = QrUnlockPayload(
      kidId: kidId,
      extraMinutes: extraMinutes,
      expiresAt: expiresAt,
      hmac: hmac,
    );

    return jsonEncode(payload.toMap());
  }

  /// Verify and extract extra minutes from a scanned unlock QR.
  /// Called from the **kids** app on the LockedScreen.
  ///
  /// Returns [extraMinutes] if the QR is valid and not expired.
  /// Throws an [Exception] with a user-friendly message if invalid.
  static int verifyAndExtract({
    required String qrData,
    required String otpSecret,
    required String expectedKidId,
  }) {
    late Map<String, dynamic> map;
    try {
      map = jsonDecode(qrData) as Map<String, dynamic>;
    } catch (_) {
      throw Exception('QR tidak valid');
    }

    if (map['type'] != 'unlock') {
      throw Exception('Bukan QR unlock yang valid');
    }

    final payload = QrUnlockPayload.fromMap(map);

    if (payload.kidId != expectedKidId) {
      throw Exception('QR ini bukan untuk perangkat ini');
    }

    if (DateTime.now().millisecondsSinceEpoch > payload.expiresAt) {
      throw Exception(
          'QR sudah kedaluwarsa. Minta orang tua untuk membuat yang baru');
    }

    final message =
        '${payload.kidId}:${payload.extraMinutes}:${payload.expiresAt}';
    final expectedHmac = _computeHmac(message, otpSecret);
    if (payload.hmac != expectedHmac) {
      throw Exception('QR tidak valid atau telah dimodifikasi');
    }

    return payload.extraMinutes;
  }

  // ─── PAIRING QR ──────────────────────────────────────────────────────────

  /// Generate a pairing QR payload string from a family ID.
  /// Called from the **parent** app's pairing screen.
  static String generatePairingQr(String familyId) {
    final payload = QrPairingPayload(familyId: familyId);
    return jsonEncode(payload.toMap());
  }

  /// Parse a scanned QR string as a pairing payload.
  /// Returns [QrPairingPayload] or null if the QR is not a pairing type.
  static QrPairingPayload? parsePairingQr(String qrData) {
    try {
      final map = jsonDecode(qrData) as Map<String, dynamic>;
      if (map['type'] != 'pair') return null;
      return QrPairingPayload.fromMap(map);
    } catch (_) {
      return null;
    }
  }

  // ─── PRIVATE ─────────────────────────────────────────────────────────────

  static String _computeHmac(String message, String secret) {
    final key = utf8.encode(secret);
    final bytes = utf8.encode(message);
    final hmac = Hmac(sha256, key);
    return base64Encode(hmac.convert(bytes).bytes);
  }
}
